### ISSUE TITLE
cannot fetch sci-libs/dcmtk-3.6.1_pre20150924

### ISSUE THREAD

**Issue by l29ah** [gerddie/gentoo-imaging#1]
404

**Comment by gerddie** [comment]
This must be a temporary thing, because I just tried _git clone_, and also traversing the source tree logged in and as anonymous user and it worked,

**Comment by l29ah** [comment]
On Tue, Mar 01, 2016 at 08:08:58AM -0800, Gert Wollny wrote:

> This must be a temporary thing, because I just tried _git clone_, and also traversing the source tree logged in and as anonymous user. 

i mean the distfile

## 

()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by gerddie** [comment]
So upsteam pulled it ... 

Well, there's always the [Debian tarball](http://http.debian.net/debian/pool/main/d/dcmtk/dcmtk_3.6.1~20150924.orig.tar.gz). 
I'll update the ebuilds shortly, and will see whether the latest upstream works.
