### ISSUE TITLE
(updated) sci-libs/gdcm-2.8.3::imaging fails to build with >dev-libs/libxslt-1.1.29-r1::gentoo

### ISSUE THREAD

**Issue by holgersson32644** [gerddie/gentoo-imaging#14]
Hi,
gdcm doesn’t build. Full build log for MAKEOPTS="-j1" is here:
https://gist.github.com/holgersson32644/a393202b4f70215a254490c69ef0b738

emerge --info app-text/docbook-xsl-ns-stylesheets:
 https://gist.github.com/holgersson32644/7714c0ba25bb6f1f4d580c3a64cfd566

The bug might be
"runtime error: file file:///usr/share/sgml/docbook/xsl-ns-stylesheets/lib/lib.xsl line 62 element variable
xsltApplySequenceConstructor: A potential infinite template recursion was detected.
You can adjust xsltMaxDepth (--maxdepth) in order to raise the maximum number of nested template calls and variables/params (currently set to 3000)."
https://gist.github.com/holgersson32644/a393202b4f70215a254490c69ef0b738#file-gistfile1-txt-L1295

**Comment by gerddie** [comment]
Unfortunately I can't reproduce the problem, for me it builds fine. 

dev-libs/libxslt: 1.1.29-r1 (the current stable version), 
app-text/docbook-xsl-ns-stylesheets: 1.78.0, 
 dev-util/cmake 3.8.2 

Actually, if you go to the original gdcm source in Utilities/doxygen/man you can find the xml files uses as input. for the failing command. To test you setup the only change needed is to replace *&version;* with some value.

Hope that helps somehow.

**Comment by holgersson32644** [comment]
Thanks, this actually helped a lot! I force-removed the package you mentioned, re-installed the stable packages (I’m globally on ~amd64) and upgraded part by part.
Looks as dev-libs/libxslt is the „faulty“ package here; I opened a bugreport on bugs.gentoo.org.

https://bugs.gentoo.org/635226

I would like to keep this issue open until the bug is fixed in the main tree, OK?

**Comment by gerddie** [comment]
Sure, best to keep the bug open.

**Comment by VolkmarGlauche** [comment]
According to Gentoo bug 635226, the build configuration should set an appropriate --maxdepth setting when calling xsltproc. I can confirm that processing gdcmdump.xml works with a --maxdepth 5000 setting (dev-libs/libxslt-1.1.30-r2, current stable).
This seems to be an upstream (gdcm) build issue but I did not yet check whether there is an upstream solution already.

**Comment by gerddie** [comment]
@VolkmarGlauche Did you report it upstream?

**Comment by olifre** [comment]
I also hit the issue just now. 

I don't find a bug report here:
https://sourceforge.net/p/gdcm/bugs/
nor see a fix in here:
https://github.com/malaterre/GDCM/blob/master/Utilities/doxygen/CMakeLists.txt
so it seems it has not been reported as of yet...

**Comment by VolkmarGlauche** [comment]
Sorry, until today I worked around the issue by compiling and merging the ebuild manually. I will report the issue upstream now.

**Comment by gerddie** [comment]
Thanks for reporting this upstream and sorry for not being more responsive, I don't really use this software any more.

**Comment by VolkmarGlauche** [comment]
See upstream: https://sourceforge.net/p/gdcm/bugs/449/

**Comment by VolkmarGlauche** [comment]
Thank you very much for this workaround. I tested a similar patch locally and it worked. Apparently, upstream did not have this problem on Debian, and it may be related to docbook or xsltproc as packaged in Gentoo rather than gdcm.
