### ISSUE TITLE
Gentoo Science collaboration castxml and itk

### ISSUE THREAD

**Issue by TheChymera** [gerddie/gentoo-imaging#21]
Hi guys, I wanted to let you know that we are trying to include your castxml ebuild in Gentoo Science, as it is becoming needed for our dependency stack. With this slightly updated ebuild:

```
# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit cmake-utils

MY_PN="CastXML"

DESCRIPTION="CastXML is a C-family abstract syntax tree XML output tool."
HOMEPAGE="https://github.com/CastXML/CastXML"
SRC_URI="https://github.com/gerddie/CastXML/archive/${PV}.tar.gz -> ${P}.tar.gz"
RESTRICT="primaryuri"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPENDS="${RDEPENDS}"
RDEPENDS="
		dev-libs/glib:2
		dev-libs/libxml2
		sys-devel/llvm:=
		"

S="${WORKDIR}/${MY_PN}-${PV}"
```

I am getting the following [build.log](https://github.com/gerddie/gentoo-imaging/files/2998870/build.log). Is it a missing dependency specification for clang?

Beyond that we are also looking to [bump ITK](https://github.com/InsightSoftwareConsortium/ITK/issues/618), which might also be interesting for you. Overall, given our recent and sustained effort to [improve support for neuroimaging software](https://riojournal.com/article/12095/), I think there might be significant overlap in our work. If you would be interested to contribute, I would be more than happy to help you out.

**Comment by TheChymera** [comment]
I tried a few more variations of the ebuild:

# llvm eclass and EAPI=6

```
# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

inherit cmake-utils llvm

MY_PN="CastXML"

DESCRIPTION="CastXML is a C-family abstract syntax tree XML output tool."
HOMEPAGE="https://github.com/CastXML/CastXML"
SRC_URI="https://github.com/gerddie/CastXML/archive/${PV}.tar.gz -> ${P}.tar.gz"
RESTRICT="primaryuri"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="${RDEPEND}"
RDEPEND="
		dev-libs/glib:2
		dev-libs/libxml2
		sys-devel/llvm:=
		sys-devel/clang:=
		"

S="${WORKDIR}/${MY_PN}-${PV}"
```

Fails with this [build.log](https://github.com/gerddie/gentoo-imaging/files/3001397/build.log).


# EAPI=7

```
# Copyright 1999-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit cmake-utils

MY_PN="CastXML"

DESCRIPTION="CastXML is a C-family abstract syntax tree XML output tool."
HOMEPAGE="https://github.com/CastXML/CastXML"
SRC_URI="https://github.com/gerddie/CastXML/archive/${PV}.tar.gz -> ${P}.tar.gz"
RESTRICT="primaryuri"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="${RDEPEND}"
RDEPEND="
		dev-libs/glib:2
		dev-libs/libxml2
		sys-devel/llvm:=
		sys-devel/clang:=
		"

S="${WORKDIR}/${MY_PN}-${PV}"
```

Fails with this [build.log](https://github.com/gerddie/gentoo-imaging/files/3001400/build.log).

**Comment by gerddie** [comment]
Sorry for not answering earlier, I'm away from my Gentoo machine (and I'm actually no longer working with ITK so that I don't have much time  to keep that monster build up to date). The errors I see point to a bug in CastXML, now because upstream doesn't want to tag releases I've forked it and tagged some of my own, but you could also make a 9999 ebuild based on the [upstream repo](http://chng.it/VxbJp4mYPc) and if that too fails to build, then you might want to file a bug upstream because it is clearly an error because of API changes.

**Comment by TheChymera** [comment]
CastXML is now available in Gentoo Science https://github.com/gentoo/sci/commit/ec3ef7df4bed9a0a64fdf6c61aeb7e2c543a6d63 Thank you very much for your help!
