### ISSUE TITLE
sci-libs/gdcm: building with system openjpeg fails

### ISSUE THREAD

**Issue by billyonthemountain** [gerddie/gentoo-imaging#3]
Its seems there are several API discrepancies between the bundled openjpeg and the system version. I tried several combination between 1.5.0-r1, 1.5.2-r1, 2.0.1-r1 and 2.1.0-r1 but to no avail. Any idea ?

Workaround : build with GDCM_USE_SYSTEM_OPENJPEG:BOOL=OFF

**Comment by gerddie** [comment]
No idea, I have 2.1.0 (-doc -static-libs -test) on amd64 with gdcm-2.6.3 and it builds without a hitch (g++-5.3.0). 
In Debian we are still at openjpeg-1.5.2, but there are also no open bugs related to this.

**Comment by gerddie** [comment]
Well, I now compiled gdcm-2.6.3 against openjpeg-2.1.0-r1 (which introduces multilib) and it also worked.

**Comment by gerddie** [comment]
I was wrong in one thing: gdcm actually compiled against openjpeg-1.5.2, testing 1.5.2-r1 now.

**Comment by gerddie** [comment]
Well, this also compiles without problems. Could you post the log of the failing build?

**Comment by billyonthemountain** [comment]
[Here](https://gist.githubusercontent.com/billyonthemountain/f1cfa30fadf284b89f8f/raw/e4612e1f0749791b530a13f2fe31dcc2bb64d02d/build.log) it is. Build is against openjpeg-2.1.0-r1. It resembles in many regards debian bug [#801228](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801228#5).

**Comment by gerddie** [comment]
I see. This is very strange, because I have both (1.5.2 and 2.1.0) installed. So my guess is that gdcm doesn't support to be build against 2.X  and when both are installed, then it might pick one randomly. I'll investigate how the version of openjpeg is selected and see whether I can fix it.

**Comment by billyonthemountain** [comment]
Looking at the errors, many of the symbols are missing the OPJ_ prefix introduced in commits [21b0ccf](https://github.com/uclouvain/openjpeg/commit/21b0ccf859d6cecdcd253ab4606261c157278980) and [84c93c2](https://github.com/uclouvain/openjpeg/commit/84c93c2fea82f13734f3ea63c0a13a011b46ddf0) prior to version 2.0. The prototype change of `opj_stream_set_user_data` come from commit [7aece5e](https://github.com/uclouvain/openjpeg/commit/7aece5e8e7d4214d140a45aca50a824ff8092924) (introduced for version 2.1). For `opj_decode`: commit [3f9fb13](https://github.com/uclouvain/openjpeg/commit/3f9fb13df66064ce9ba707e48a8c3ead9556aa49).

It seems the same [issue](http://beastie.tardisi.com/patches/2014/05/31/gdcm-update-for-openjpeg15/) hit FreeBSD; `opj_get_reversible` never existed in openjpeg's codebase. I'll try to port their patches and report back.

**Comment by gerddie** [comment]
Okay, found it. The FindOpenJPEG  implemented in gdcm searched simply for the file openjpeg.h and deducts the include path from this. Which is used depends on on whether it firsts finds the one from version 1.5 or the one from version 2.1. I'll report this to gdcm upstream and think about how CMake can be made to select a specific openjpeg version.

**Comment by gerddie** [comment]
[Reported](https://sourceforge.net/p/gdcm/bugs/376/). BTW, there is also request to [support 2.1.0](https://sourceforge.net/p/gdcm/bugs/356/). 

Currently, the FindOpenJPEG.cmake file searches only for the library name **openjpeg**, which indicates 1.X series, so when you port gdcm to use 2.1, this must also be changed.
