### ISSUE TITLE
sci-libs/vtk file collision with dev-python/six

### ISSUE THREAD

**Issue by olifre** [gerddie/gentoo-imaging#7]
vtk seems to use a bundled version of six :-(. 
Seemingly to build a bundled version of "autobahn", both are separately in portage... 
I get on install:
```
 * Detected file collision(s):
 * 
 *      /usr/lib64/python2.7/site-packages/six.py
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * dev-python/six-1.10.0:0::gentoo
 *      /usr/lib64/python2.7/site-packages/six.py
```
Sadly `dev-python/six` is used a lot by many other python deps, so I can not remove it. 

And finally I'm slowly giving up on getting `sci-visualization/ginkgocadx` due to too many broken dependencies.

**Comment by gerddie** [comment]
Strange, I have both,  *dev-python/six-0.10.0* and *sci-libs/vtk-6.3.0-r2* installed. The latter with use flags "X boost ffmpeg imaging python qt5 rendering smp tbb theora -R -all-modules -aqua -cg -doc -examples -gdal -java -json -kaapi -mpi -mysql -odbc -offscreen -postgres -tcl -test -tk -views -web -xdmf2" PYTHON_TARGETS="python2_7"

**Comment by olifre** [comment]
That's a good hint! I tried with:
`X boost cg ffmpeg java mpi mysql odbc postgres python qt5 rendering smp tbb tcl theora tk web`
(and `VIDEO_CARDS="nvidia"`). 
Since autobahn is related to web-stuff, I guess I'll try to remove "web" first and report back wether that helped...

**Comment by gerddie** [comment]
There are actually options  VTK_USE_SYSTEM_SIX and VTK_USE_SYSTEM_AUTOBAHN. It seem they come up when web is enables, but I'll have ti check that further,

**Comment by olifre** [comment]
Indeed I can now confirm that without `web` the collision is gone. 
The package then installs only python-modules in
`/usr/lib64/python2.7/site-packages/vtk/`
as expected. 
So I'd guess that for web, another dependency on six / autobahn (maybe autobahn alone is sufficient, I think it pulls in six anyways) and setting the `USE_SYSTEM` variables could be the solution.

**Comment by gerddie** [comment]
Actually, *autobahn* was already set to use_system, I've now added *six* as well and will see how it goes.
