### ISSUE TITLE
=sci-libs/itk-4.10.1 needs `-DITK_USE_SYSTEM_CASTXML=ON`

### ISSUE THREAD

**Issue by olifre** [gerddie/gentoo-imaging#8]
I just got:
```
CMake Error at CMake/ITKDownloadSetup.cmake:14 (message):
  Attempted to download CastXML when ITK_FORBID_DOWNLOADS is ON
Call Stack (most recent call first):
  Wrapping/Generators/CastXML/CMakeLists.txt:51 (itk_download_attempt_check)
```
during configure of `=sci-libs/itk-4.10.1`, even though CastXML is installed (and was correctly pulled in as dependency). 
Setting `-DITK_USE_SYSTEM_CASTXML=ON` fixes that and configure runs through (still compiling, though) - I'm not sure if older versions are also affected. 
For reference, I installed with:
`USE="fftw python sse2 -debug -doc -examples -itkv3compat -review {-test} -vtkglue"`.

**Comment by gerddie** [comment]
Well, I have to admit it has been some time since I build ITK with python support on Gentoo (because it takes forever to compile). If one doesn't  really need it, it is better to disable it. 

Anyway, thanks for digging though this and reporting all the bugs.

**Comment by olifre** [comment]
> If one doesn't really need it, it is better to disable it.

That was a good hint - after a good hour on my i7 in which I the package only made it to 81% (and the scale seemed to be highly non-linear), I finally stopped it, removed the python-flag, and it was done in a few minutes. 
And finally, `sci-visualization/ginkgocadx` is running well. Thanks a lot for all the packaging work and the fast responses! 👍
