### ISSUE TITLE
[PR #10] vtk-7.1.0-r1 is broken (comments in SRC_URI) + ginkgocadx needs opengl <2

### ISSUE THREAD

**Issue by holgersson32644** [gerddie/gentoo-imaging#9]
Hi,

you commented out *inside* SRC_URI - this doesn't work. Instead, '#' is taken as part of the distfiles,
which causes some trouble.

A workaround would close the SRC_URI *before* writing the comments/'#'.

Greetings,
holgersson

**Comment by gerddie** [comment]
Thanks for the pull request. It is a temporary workaround only, because I am currently on a volume limited internet connection, I wanted to disable downloading the test data. As soon as I'm back to full internet access I'll re-enable these urls.

**Comment by gerddie** [comment]
I've updated to the new version 7.1.1 and also re-enabled the data files.
